### ISSUE TITLE
Stripe API Key Request

### ISSUE THREAD

**Issue by matteo-gatti** [matteo-gatti/IS2-MSGC-Parket#15]
attualmente non è possibile prenotare per un problema con le api key di stripe,  di seguito il codice d'errore loggato.

StripeAuthenticationError: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.

https://github.com/stripe/stripe-dotnet/issues/214, magari torna utile per risolvere il problema

**Comment by matteo-gatti** [comment]
inserire key nel .env

**Comment by ericsua** [comment]
Lol
